"""Causality System — dynamic causal chains with LRU+TTL eviction.

Extends the original PlotHookManager with dynamic, LLM-generated causal chains.
Causal chains are created by the EventDirector during narrative generation
(zero extra LLM calls) and matched against future events using keyword BM25.

Key design principles:
- Max 10 active causal chains (LRU+TTL eviction)
- Chain creation: embedded in EventDirector's JSON output (optional field)
- Chain matching: keyword intersection (jieba-powered, same as event system)
- Zero additional LLM calls — matching is pure rule-based
- Backward compatible: preserves original PlotHook static mechanism
"""
from __future__ import annotations

import uuid
import random
import logging
from typing import Optional, List, TYPE_CHECKING

from pydantic import BaseModel

if TYPE_CHECKING:
    from ..models import GameState

logger = logging.getLogger(__name__)

# ── Configuration ─────────────────────────────────────────────────────────

MAX_CAUSAL_CHAINS = 10
DEFAULT_MAX_WAIT_YEARS = 150
URGENCY_ESCALATION_THRESHOLD = 50  # Years before TTL when urgency starts climbing

# Minimum realm required to resolve specific hook types
# If player realm < min_realm, forced resolution is deferred (延期) instead of triggered
_HOOK_MIN_REALM = {
    "tribulation_preparation": 4,  # 至少元婴才能解决渡劫准备
    "inner_demon": 2,              # 筑基以上才能解决心魔
    "blood_feud": 2,               # 筑基以上才能了结血仇
    "master_secret": 3,            # 金丹以上揭开师父秘密
    "forbidden_zone": 3,           # 金丹以上探索禁地
    "soul_debt": 4,                # 元婴以上偿还魂债
    "sect_crisis": 2,              # 筑基以上应对宗门危机
    "ancient_inheritance": 3,      # 金丹以上接受上古传承
}


# ── Data Models ───────────────────────────────────────────────────────────

class CausalChain(BaseModel):
    """A dynamic causal thread generated by LLM during narrative."""
    chain_id: str
    cause_event_text: str          # Original event text that created this chain
    cause_keywords: list[str]      # Keywords extracted from cause event
    expected_resolution: str       # LLM-described expected resolution direction
    resolution_keywords: list[str] # Keywords for matching resolution events
    npc_id: str = ""
    npc_name: str = ""
    created_age: int = 0
    last_accessed_age: int = 0     # LRU basis (updated on match attempts)
    max_wait_years: int = DEFAULT_MAX_WAIT_YEARS
    urgency: float = 1.0           # Increases over time
    is_resolved: bool = False
    resolved_age: int = 0


class PlotHook(BaseModel):
    """A static narrative thread (backward-compatible with original system)."""
    hook_id: str
    description: str
    created_age: int
    npc_id: str = ""
    npc_name: str = ""
    resolution_tags: list = []
    max_wait_years: int = 100
    is_resolved: bool = False
    resolved_age: int = 0


# ── CausalityManager ─────────────────────────────────────────────────────

class CausalityManager:
    """Manages both static plot hooks and dynamic causal chains.

    Replaces PlotHookManager with full backward compatibility plus
    the new dynamic causal chain system.
    """

    # ── Static PlotHook methods (backward compatible) ─────────────────

    def process_event(self, state: "GameState", event: dict) -> None:
        """Process static hooks from event JSON fields (backward compat)."""
        # Check if event creates a static hook
        creates = event.get("creates_hook")
        if creates:
            self._create_static_hook(
                state,
                hook_id=creates.get("id", ""),
                description=creates.get("description", ""),
                max_wait=creates.get("max_wait", 100),
                npc_id=event.get("involved_npc_id", ""),
                npc_name=event.get("involved_npc", ""),
            )

        # Check if event resolves a static hook
        resolves_id = event.get("resolves_hook")
        if resolves_id:
            self._resolve_static_hook(state, resolves_id)

        # Check if event resolves any dynamic causal chain (by keyword match)
        self._check_chain_resolution(state, event)

    def _create_hook(
        self, state: "GameState", hook_id: str, description: str,
        max_wait: int = 100, npc_id: str = "", npc_name: str = "",
    ) -> None:
        """Alias for backward compatibility with PlotHookManager."""
        self._create_static_hook(state, hook_id, description, max_wait, npc_id, npc_name)

    def _create_static_hook(
        self, state: "GameState", hook_id: str, description: str,
        max_wait: int = 100, npc_id: str = "", npc_name: str = "",
    ) -> None:
        """Plant a static plot hook."""
        for hook in state.plot_hooks:
            if hook.get("hook_id") == hook_id:
                return

        hook = PlotHook(
            hook_id=hook_id,
            description=description,
            created_age=state.age,
            npc_id=npc_id,
            npc_name=npc_name,
            max_wait_years=max_wait,
        ).model_dump()

        state.plot_hooks.append(hook)
        logger.debug("Created static hook: %s at age %d", hook_id, state.age)

    def _resolve_static_hook(self, state: "GameState", hook_id: str) -> None:
        """Resolve a static plot hook."""
        for i, hook in enumerate(state.plot_hooks):
            if hook.get("hook_id") == hook_id and not hook.get("is_resolved"):
                hook["is_resolved"] = True
                hook["resolved_age"] = state.age
                state.resolved_hooks.append(hook)
                state.plot_hooks.pop(i)
                logger.debug("Resolved static hook: %s at age %d", hook_id, state.age)

                # Clean NPC relationship hooks
                npc_id = hook.get("npc_id", "")
                if npc_id:
                    for rel in state.relationships:
                        if rel.get("npc_id") == npc_id:
                            hooks = rel.get("unresolved_hooks", [])
                            if hook_id in hooks:
                                hooks.remove(hook_id)
                            break
                return

    # ── Dynamic Causal Chain methods ──────────────────────────────────

    def create_causal_chain(
        self, state: "GameState", chain_data: dict, event: dict
    ) -> None:
        """Create a dynamic causal chain from EventDirector output.

        Args:
            state: Current game state
            chain_data: Dict with {cause, expected_resolution, keywords}
            event: The event that triggered this chain creation
        """
        from .event_system import extract_keywords

        cause_text = chain_data.get("cause", event.get("text", ""))
        expected = chain_data.get("expected_resolution", "")
        raw_keywords = chain_data.get("keywords", [])

        if not expected:
            return

        # Extract keywords from cause event
        cause_keywords = extract_keywords(cause_text, max_keywords=8)

        # Use provided keywords as resolution keywords, supplement if too few
        resolution_keywords = list(raw_keywords)[:8]
        if len(resolution_keywords) < 2:
            resolution_keywords = extract_keywords(expected, max_keywords=6)

        # Evict if at max capacity (LRU: remove least recently accessed)
        self._evict_chains(state)

        chain = CausalChain(
            chain_id=f"chain_{uuid.uuid4().hex[:6]}",
            cause_event_text=cause_text[:80],
            cause_keywords=cause_keywords,
            expected_resolution=expected[:60],
            resolution_keywords=resolution_keywords,
            npc_id=event.get("involved_npc_id", ""),
            npc_name=event.get("involved_npc", ""),
            created_age=state.age,
            last_accessed_age=state.age,
        ).model_dump()

        state.causal_chains.append(chain)
        logger.info(
            "Created causal chain: '%s' -> '%s' (keywords: %s)",
            cause_text[:30], expected[:30], resolution_keywords[:5]
        )

    def get_chain_weight_adjustments(self, state: "GameState") -> dict[str, float]:
        """Calculate weight boosts for events that match active causal chains.

        Returns: dict mapping event keyword patterns to multipliers.
        Used by EventDirector to boost matching candidates.
        """
        adjustments: dict[str, float] = {}

        for chain in state.causal_chains:
            if chain.get("is_resolved"):
                continue

            # Update urgency based on elapsed time
            created = chain.get("created_age", 0)
            max_wait = chain.get("max_wait_years", DEFAULT_MAX_WAIT_YEARS)
            years_elapsed = state.age - created
            years_remaining = max_wait - years_elapsed

            if years_remaining <= 0:
                urgency = 10.0
            elif years_remaining < URGENCY_ESCALATION_THRESHOLD:
                urgency = 3.0 + (URGENCY_ESCALATION_THRESHOLD - years_remaining) * 0.14
            else:
                urgency = 1.5

            chain["urgency"] = urgency

            # Map resolution keywords to weight multiplier
            for kw in chain.get("resolution_keywords", []):
                existing = adjustments.get(kw, 1.0)
                adjustments[kw] = max(existing, urgency)

        return adjustments

    def match_candidates_with_chains(
        self, state: "GameState", candidates: list[dict]
    ) -> list[dict]:
        """Apply causal chain weight boosts to candidate events.

        Modifies candidate weights in-place based on keyword overlap
        with active causal chain resolution keywords.

        Returns the same candidates list (modified).
        """
        active_chains = [c for c in state.causal_chains if not c.get("is_resolved")]
        if not active_chains:
            return candidates

        # Update urgency for all active chains before matching
        for chain in active_chains:
            created = chain.get("created_age", 0)
            max_wait = chain.get("max_wait_years", DEFAULT_MAX_WAIT_YEARS)
            years_elapsed = state.age - created
            years_remaining = max_wait - years_elapsed
            if years_remaining <= 0:
                chain["urgency"] = 10.0
            elif years_remaining < URGENCY_ESCALATION_THRESHOLD:
                chain["urgency"] = 3.0 + (URGENCY_ESCALATION_THRESHOLD - years_remaining) * 0.14
            else:
                chain["urgency"] = 1.5

        for cand in candidates:
            ev = cand["event"]
            ev_keywords = set(ev.get("_keywords", []))
            ev_text = ev.get("text", "")

            total_boost = 1.0
            for chain in active_chains:
                res_kws = set(chain.get("resolution_keywords", []))
                # Dimension 1: keyword intersection
                overlap = len(res_kws & ev_keywords)
                # Dimension 2: keyword in text (broader match)
                text_hits = sum(1 for kw in res_kws if kw in ev_text and kw not in ev_keywords)
                match_score = overlap + text_hits

                if match_score >= 3:
                    boost = chain.get("urgency", 1.5) * 2.0
                elif match_score >= 2:
                    boost = chain.get("urgency", 1.5) * 1.5
                elif match_score >= 1:
                    boost = chain.get("urgency", 1.5)
                else:
                    boost = 1.0

                total_boost = max(total_boost, boost)

                # Update last_accessed_age for LRU tracking
                if match_score >= 1:
                    chain["last_accessed_age"] = state.age

            cand["weight"] *= total_boost

        return candidates

    def _check_chain_resolution(self, state: "GameState", event: dict) -> None:
        """Check if a processed event resolves any active causal chain."""
        from .event_system import extract_keywords

        event_keywords = set(event.get("_keywords", []))
        if not event_keywords:
            event_keywords = set(extract_keywords(event.get("text", ""), max_keywords=8))

        event_text = event.get("text", "")

        for chain in state.causal_chains:
            if chain.get("is_resolved"):
                continue

            res_kws = set(chain.get("resolution_keywords", []))
            overlap = len(res_kws & event_keywords)
            text_hits = sum(1 for kw in res_kws if kw in event_text and kw not in event_keywords)
            match_score = overlap + text_hits

            # Threshold for resolution: need strong match (>= 3 keywords)
            if match_score >= 3:
                chain["is_resolved"] = True
                chain["resolved_age"] = state.age
                logger.info(
                    "Causal chain resolved: '%s' at age %d (score=%d)",
                    chain.get("expected_resolution", "")[:30], state.age, match_score
                )

    def _evict_chains(self, state: "GameState") -> None:
        """Evict chains when at capacity: resolved > TTL expired > LRU."""
        chains = state.causal_chains

        # Remove resolved chains first
        chains[:] = [c for c in chains if not c.get("is_resolved")]

        # Remove TTL-expired chains
        if len(chains) >= MAX_CAUSAL_CHAINS:
            chains[:] = [
                c for c in chains
                if (state.age - c.get("created_age", 0)) < c.get("max_wait_years", DEFAULT_MAX_WAIT_YEARS)
            ]

        # LRU eviction if still over limit
        while len(chains) >= MAX_CAUSAL_CHAINS:
            # Find least recently accessed
            oldest_idx = 0
            oldest_access = chains[0].get("last_accessed_age", 0)
            for i, c in enumerate(chains[1:], 1):
                access = c.get("last_accessed_age", 0)
                if access < oldest_access:
                    oldest_access = access
                    oldest_idx = i
            evicted = chains.pop(oldest_idx)
            logger.debug("Evicted causal chain (LRU): %s", evicted.get("chain_id", ""))

    # ── Expiring hooks/chains check ───────────────────────────────────

    def check_expiring_hooks(self, state: "GameState") -> List[dict]:
        """Find static hooks that have expired their max_wait_years."""
        expiring = []
        for hook in state.plot_hooks:
            if hook.get("is_resolved"):
                continue
            created_age = hook.get("created_age", 0)
            max_wait = hook.get("max_wait_years", 100)
            if (state.age - created_age) >= max_wait:
                expiring.append(hook)
        return expiring

    def check_expiring_chains(self, state: "GameState") -> List[dict]:
        """Find dynamic causal chains that have expired."""
        expiring = []
        for chain in state.causal_chains:
            if chain.get("is_resolved"):
                continue
            created_age = chain.get("created_age", 0)
            max_wait = chain.get("max_wait_years", DEFAULT_MAX_WAIT_YEARS)
            if (state.age - created_age) >= max_wait:
                expiring.append(chain)
        return expiring

    def generate_forced_resolution(self, state: "GameState", hook: dict) -> Optional[dict]:
        """Generate a resolution event for an expired hook or chain.

        If player realm is below the hook's minimum requirement, the hook is
        deferred (max_wait extended by 50 years) rather than force-resolved.
        """
        hook_id = hook.get("hook_id", hook.get("chain_id", "unknown"))
        description = hook.get("description", hook.get("expected_resolution", "一段往事"))
        npc_name = hook.get("npc_name", "")

        # Realm gate: defer if player not strong enough
        min_realm = _HOOK_MIN_REALM.get(hook_id, 0)
        current_realm = getattr(state, "realm", 0)
        if current_realm < min_realm:
            # Extend TTL instead of forcing resolution
            hook["max_wait_years"] = hook.get("max_wait_years", 100) + 50
            logger.debug(
                "Deferred hook '%s' resolution: realm %d < required %d, extended wait to %d",
                hook_id, current_realm, min_realm, hook["max_wait_years"]
            )
            return None

        # Realm-aware narrative templates
        if current_realm >= 4:
            # 高境界：气势磅礴的了结
            if npc_name:
                templates = [
                    f"历经百年修行，你已有足够实力了结{description}的因果——与{npc_name}的这段缘分终于尘埃落定",
                    f"以元婴之境的修为，你终于有能力解决{description}之事，{npc_name}也对此释然",
                ]
            else:
                templates = [
                    f"历经百年修行，当年{description}的执念，在元婴大能之下终于彻底化解",
                    f"以你如今的境界，{description}一事不过是修道路上的一段插曲，轻松了结",
                ]
        else:
            # 中低境界：传统叙事
            if npc_name:
                templates = [
                    f"多年来的执念终于有了结果——{description}的因果，在与{npc_name}的一次重逢中化解",
                    f"时过境迁，当年{description}之事终于尘埃落定",
                    f"你与{npc_name}的这段缘分，在岁月流转中渐渐淡去",
                ]
            else:
                templates = [
                    f"多年前{description}的执念，在一次静修中悠然释怀",
                    f"时过境迁，{description}一事终于有了交代",
                    f"你在惟恋之时回忆起{description}，心中释然",
                ]

        resolution_text = random.choice(templates)

        event = {
            "id": f"causality_resolve_{hook_id}_{uuid.uuid4().hex[:4]}",
            "text": resolution_text,
            "expanded_text": resolution_text,
            "category": "common",
            "event_type": "important",
            "tags": ["causality_resolution"],
            "effects": {"willpower": 1},
            "resolves_hook": hook_id if hook.get("hook_id") else "",
        }

        if hook.get("npc_id"):
            event["involved_npc_id"] = hook["npc_id"]
            event["involved_npc"] = npc_name

        # Mark the chain as resolved
        if hook.get("chain_id"):
            hook["is_resolved"] = True
            hook["resolved_age"] = state.age

        return event

    # ── Weight adjustments for static hooks (backward compat) ─────────

    def get_weight_adjustments(self, state: "GameState") -> dict:
        """Calculate weight multipliers for events resolving static hooks."""
        adjustments = {}
        for hook in state.plot_hooks:
            if hook.get("is_resolved"):
                continue

            hook_id = hook.get("hook_id", "")
            created_age = hook.get("created_age", 0)
            max_wait = hook.get("max_wait_years", 100)
            years_elapsed = state.age - created_age
            years_remaining = max_wait - years_elapsed

            if years_remaining <= 0:
                adjustments[hook_id] = 10.0
            elif years_remaining < 20:
                adjustments[hook_id] = 5.0
            else:
                adjustments[hook_id] = 3.0

        return adjustments

    # ── AI context builders ───────────────────────────────────────────

    def get_hooks_context_for_ai(self, state: "GameState") -> str:
        """Build context string about active static hooks for AI prompts."""
        if not state.plot_hooks:
            return ""

        lines = ["未了之事:"]
        for hook in state.plot_hooks:
            if hook.get("is_resolved"):
                continue
            desc = hook.get("description", "")
            npc = hook.get("npc_name", "")
            created = hook.get("created_age", 0)
            years_ago = state.age - created

            line = f"  - {desc}"
            if npc:
                line += f" (与{npc}相关)"
            line += f" [{years_ago}年前埋下]"
            lines.append(line)

        return "\n".join(lines) if len(lines) > 1 else ""

    def get_chains_context_for_ai(self, state: "GameState") -> str:
        """Build context string about active causal chains for AI prompts."""
        active = [c for c in state.causal_chains if not c.get("is_resolved")]
        if not active:
            return ""

        lines = ["因果暗线:"]
        for chain in active[:5]:  # Limit context to top 5
            cause = chain.get("cause_event_text", "")[:40]
            resolution = chain.get("expected_resolution", "")[:40]
            npc = chain.get("npc_name", "")
            years_ago = state.age - chain.get("created_age", 0)
            urgency = chain.get("urgency", 1.0)

            urgency_mark = ""
            if urgency >= 5.0:
                urgency_mark = " [紧迫!]"
            elif urgency >= 3.0:
                urgency_mark = " [渐近]"

            line = f"  - 起因: {cause} → 待解: {resolution}"
            if npc:
                line += f" (涉及{npc})"
            line += f" [{years_ago}年前]{urgency_mark}"
            lines.append(line)

        return "\n".join(lines)
