"""Choice Generator — LLM-powered dynamic choice branch generation.

Replaces the old fixed-branch system with real-time contextual choices
generated by DeepSeek. Falls back to pre-defined templates when LLM
is unavailable.

Design:
- should_generate_choice() decides if an event warrants choices
- generate_choices() calls LLM or falls back to templates
- Each choice includes immediate effects + long-term consequence tags
"""
from __future__ import annotations

import json
import logging
import random
from typing import Optional, TYPE_CHECKING

from .ai.prompt_templates import CHOICE_GENERATION_SYSTEM, CHOICE_GENERATION_USER

if TYPE_CHECKING:
    from ..models import GameState
    from .ai.llm_client import LLMClient
    from .ai.prompt_builder import PromptBuilder
    from .npc import NPCManager
    from .plot_hooks import PlotHookManager

logger = logging.getLogger(__name__)


# ── Fallback templates (when LLM is unavailable) ─────────────────────

_FALLBACK_TEMPLATES = {
    "danger": [
        {
            "text": "奋起迎战",
            "success_rate": 55,
            "check_attribute": "constitution",
            "effects": {"cultivation": 30, "willpower": 1},
            "result_text": "你鼓起勇气迎战而上，以命搏命之间竟悟得一线生机，修为暴涨！",
            "failure_effects": {"cultivation": 5, "constitution": -2},
            "failure_text": "你奋力迎战，却不敌对手，身负重伤勉强保命。虽败犹有所得，但代价不小。",
            "consequence_tag": "历经险难",
            "consequence_desc": "这次生死搏杀磨砺了你的心志",
        },
        {
            "text": "避其锋芒",
            "success_rate": 80,
            "check_attribute": "comprehension",
            "effects": {"comprehension": 1, "cultivation": 5},
            "result_text": "你选择以退为进，远遁而去。脱身之际观敌手法，竟也有所领悟。",
            "failure_effects": {"cultivation": -5},
            "failure_text": "你想要避退，却被对手看穿意图，虽最终逃脱，却颇为狼狈。",
            "consequence_tag": "",
            "consequence_desc": "",
        },
        {
            "text": "以智取胜",
            "success_rate": 45,
            "check_attribute": "comprehension",
            "effects": {"cultivation": 20, "willpower": 1, "charisma": 1},
            "result_text": "你运用巧计化解了危机，以弱胜强，令旁观者啧啧称奇。",
            "failure_effects": {"cultivation": 3, "willpower": -1},
            "failure_text": "你的计策被对手识破，反而陷入更被动的局面。好在你急中生智，勉强脱困。",
            "consequence_tag": "智者之名",
            "consequence_desc": "你的智谋之名开始在修仙界流传",
        },
    ],
    "fortune": [
        {
            "text": "独享机缘",
            "success_rate": 50,
            "check_attribute": "fortune",
            "effects": {"cultivation": 40},
            "result_text": "你将机缘尽数收入囊中，修为大涨！天地灵气如百川归海，尽入体内。",
            "failure_effects": {"cultivation": 10, "fortune": -1},
            "failure_text": "你贪心太过，灵气反噬之下只吸收了一小部分。隐约觉得福缘有所折损。",
            "consequence_tag": "贪念之种",
            "consequence_desc": "独占机缘的行为可能在日后引来嫉妒",
        },
        {
            "text": "分享机缘",
            "success_rate": 85,
            "check_attribute": "charisma",
            "effects": {"cultivation": 15, "charisma": 2},
            "result_text": "你将机缘与同行之人分享，众人感激不已。你的慷慨赢得了信义与人心。",
            "failure_effects": {"cultivation": 8, "charisma": 1},
            "failure_text": "你本欲分享机缘，但对方似乎并不领情。虽有些尴尬，好歹自己也有所收获。",
            "consequence_tag": "仁义之名",
            "consequence_desc": "你的慷慨之名开始传播",
        },
        {
            "text": "谨慎观望",
            "success_rate": 70,
            "check_attribute": "comprehension",
            "effects": {"comprehension": 2, "fortune": 1},
            "result_text": "你没有急于行动，仔细观察后发现了隐藏的更大机缘！悟性大增。",
            "failure_effects": {"comprehension": 1},
            "failure_text": "你观望太久，机缘在犹豫中流逝了大半。虽略有所悟，但总觉错失良机。",
            "consequence_tag": "",
            "consequence_desc": "",
        },
    ],
    "important": [
        {
            "text": "积极参与",
            "success_rate": 60,
            "check_attribute": "charisma",
            "effects": {"cultivation": 20, "charisma": 1},
            "result_text": "你主动投身其中，展现出不凡的风采，赢得了众人的认可与赞叹。",
            "failure_effects": {"cultivation": 5, "charisma": -1},
            "failure_text": "你积极参与，却因经验不足而出了纰漏。虽未酿成大错，但颜面有损。",
            "consequence_tag": "",
            "consequence_desc": "",
        },
        {
            "text": "冷眼旁观",
            "success_rate": 75,
            "check_attribute": "willpower",
            "effects": {"willpower": 1, "comprehension": 1},
            "result_text": "你选择置身事外，在远处静静观察。以旁观者视角审视全局，心有所悟。",
            "failure_effects": {"willpower": 1},
            "failure_text": "你想要旁观，却被卷入其中不得脱身。虽未受损，但也错失了从容观察的机会。",
            "consequence_tag": "",
            "consequence_desc": "",
        },
    ],
}


class ChoiceGenerator:
    """Generates dynamic choice branches for game events using LLM."""

    def __init__(
        self,
        llm_client: "LLMClient",
        prompt_builder: "PromptBuilder",
        npc_manager: "NPCManager",
        hook_manager: "PlotHookManager",
    ):
        self.llm_client = llm_client
        self.prompt_builder = prompt_builder
        self.npc_manager = npc_manager
        self.hook_manager = hook_manager

    def should_generate_choice(self, event: dict, state: "GameState") -> bool:
        """Decide whether an event should trigger a player choice.

        Conditions:
        - Event type is important/danger/fortune
        - No choice currently pending
        - Probability check: ~40% base, modified by tension
        """
        if state.pending_choice is not None:
            return False

        event_type = event.get("event_type", "normal")
        if event_type not in ("important", "danger", "fortune"):
            return False

        # Skip chain events and hook resolutions
        if event.get("resolves_hook") or "hook_resolution" in event.get("tags", []):
            return False

        # Skip events that already have branches (pre-defined)
        if event.get("branches"):
            return True  # Use existing branches

        # Probability based on tension
        tension = state.tension
        if tension >= 70:
            chance = 0.60  # High tension → more choices
        elif tension <= 30:
            chance = 0.20  # Low tension → fewer choices
        else:
            chance = 0.40  # Normal

        return random.random() < chance

    def generate_choices(self, event: dict, state: "GameState") -> list[dict]:
        """Generate 2-3 choice branches for an event.

        Tries LLM first, falls back to templates.
        Returns list of branch dicts.
        """
        # If event already has branches, use them
        if event.get("branches"):
            return event["branches"]

        # Try LLM generation
        if self.llm_client.available:
            branches = self._generate_via_llm(event, state)
            if branches:
                return branches

        # Fallback to templates
        return self._generate_fallback(event, state)

    def _generate_via_llm(self, event: dict, state: "GameState") -> Optional[list[dict]]:
        """Generate choices using LLM."""
        try:
            system_prompt, user_prompt = self._build_choice_prompt(event, state)
            raw = self.llm_client.generate_sync(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                max_tokens=600,
                temperature=0.85,
            )

            if not raw:
                logger.debug("LLM returned empty response for choice generation")
                return None

            # Clean markdown fences if present
            cleaned = raw.strip()
            if cleaned.startswith("```"):
                lines = cleaned.split("\n")
                lines = [l for l in lines if not l.strip().startswith("```")]
                cleaned = "\n".join(lines)

            branches = json.loads(cleaned)
            if not isinstance(branches, list) or len(branches) < 2:
                logger.warning("LLM returned invalid branch format: %s", raw[:200])
                return None

            # Validate and sanitize each branch
            valid_branches = []
            for b in branches[:3]:  # Cap at 3
                if not isinstance(b, dict):
                    continue
                if "text" not in b:
                    continue

                # Sanitize check_attribute
                check_attr = str(b.get("check_attribute", ""))
                if check_attr not in ("constitution", "comprehension", "fortune", "charisma", "willpower"):
                    check_attr = ""

                branch = {
                    "text": str(b.get("text", ""))[:20],
                    "success_rate": max(10, min(95, int(b.get("success_rate", 60)))),
                    "check_attribute": check_attr,
                    "effects": self._sanitize_effects(b.get("effects", {})),
                    "result_text": str(b.get("result_text", ""))[:200],
                    "failure_effects": self._sanitize_effects(b.get("failure_effects", {})),
                    "failure_text": str(b.get("failure_text", ""))[:200],
                    "consequence_tag": str(b.get("consequence_tag", "")),
                    "consequence_desc": str(b.get("consequence_desc", "")),
                }
                valid_branches.append(branch)

            if len(valid_branches) >= 2:
                logger.info("LLM generated %d choice branches", len(valid_branches))
                return valid_branches

            return None

        except (json.JSONDecodeError, KeyError, TypeError) as e:
            logger.warning("Failed to parse LLM choice output: %s", e)
            return None

    @staticmethod
    def _sanitize_effects(effects: dict) -> dict:
        """Sanitize and clamp effect values."""
        if not isinstance(effects, dict):
            return {}

        allowed = {
            "cultivation": (-30, 50),
            "constitution": (-3, 3),
            "comprehension": (-3, 3),
            "fortune": (-3, 3),
            "charisma": (-3, 3),
            "willpower": (-3, 3),
        }

        sanitized = {}
        for key, (lo, hi) in allowed.items():
            val = effects.get(key)
            if val is not None:
                try:
                    sanitized[key] = max(lo, min(hi, int(val)))
                except (ValueError, TypeError):
                    pass

        # Handle add_tag
        tag = effects.get("add_tag")
        if tag and isinstance(tag, str):
            sanitized["add_tag"] = tag[:20]

        return sanitized

    def _build_choice_prompt(self, event: dict, state: "GameState") -> tuple[str, str]:
        """Build system+user prompt pair for choice generation."""
        from ..models import REALM_NAMES, Realm

        realm_name = REALM_NAMES.get(Realm(state.realm), "未知")

        # Sect info
        sect_info = "散修"
        if state.sect_membership:
            mem = state.sect_membership
            # Find sect name
            sects = state.sect_world.get("sects", {})
            sect = sects.get(mem.get("sect_id", ""), {})
            if sect:
                sect_info = f"{sect.get('name', '未知')}·{mem.get('rank', '弟子')}"

        # NPC relationships
        npc_lines = []
        for rel in state.relationships[:5]:
            npc_id = rel.get("npc_id", "")
            npc = state.npc_registry.get(npc_id, {})
            if npc:
                name = npc.get("name", "未知")
                rel_type = rel.get("relation_type", "路人")
                sentiment = rel.get("sentiment", 0)
                npc_lines.append(f"- {name}({rel_type}, 好感{sentiment})")
        npc_str = "\n".join(npc_lines) if npc_lines else "暂无重要人际关系"

        # Unresolved hooks
        hook_str = self.hook_manager.get_hooks_context_for_ai(state) if self.hook_manager else ""
        if not hook_str:
            hook_str = "无"

        # Biography
        bio = state.biography_summary or "尚无传记"

        attrs = state.attributes
        system_prompt = CHOICE_GENERATION_SYSTEM

        user_prompt = CHOICE_GENERATION_USER.format(
            event_text=event.get("text", ""),
            event_type=event.get("event_type", "normal"),
            realm_name=realm_name,
            age=state.age,
            gender="男" if state.gender == "male" else "女",
            constitution=attrs.constitution,
            comprehension=attrs.comprehension,
            fortune=attrs.fortune,
            charisma=attrs.charisma,
            willpower=attrs.willpower,
            sect_info=sect_info,
            tension=int(state.tension),
            npc_relationships=npc_str,
            biography=bio,
            unresolved_hooks=hook_str,
        )

        return system_prompt, user_prompt

    def _generate_fallback(self, event: dict, state: "GameState") -> list[dict]:
        """Generate fallback choices from pre-defined templates."""
        event_type = event.get("event_type", "normal")
        templates = _FALLBACK_TEMPLATES.get(event_type)

        if not templates:
            templates = _FALLBACK_TEMPLATES["important"]

        # Return 2-3 templates, slightly randomized
        selected = random.sample(templates, min(len(templates), random.choice([2, 3])))

        # Scale effects by realm
        realm_scale = max(1, state.realm)
        result = []
        for t in selected:
            branch = dict(t)
            scaled_effects = {}
            for k, v in branch.get("effects", {}).items():
                if isinstance(v, (int, float)):
                    scaled_effects[k] = int(v * (1 + (realm_scale - 1) * 0.3))
                else:
                    scaled_effects[k] = v
            branch["effects"] = scaled_effects
            result.append(branch)

        return result
